# common setting
spring:
  application:
    name: TicketingConsumer

  main:
    web-application-type: none
  docker:
    compose:
      enabled: false

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
      separator: ";"

cloud:
  aws:
    region:
      static: ${AWS_REGION:us-west-2}
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:dummy}
      secret-key: ${AWS_SECRET_ACCESS_KEY:dummy}
    endpoint:
      sqs: ${AWS_SQS_ENDPOINT:}

sqs:
  queue:
    ticket-sql-name: ${SQS_TICKET_SQL_QUEUE:ticketSQL}

logging:
  file:
    name: ./logs/ticketing-platform.log
  level:
    root: INFO
    org.java.rabbitcombinedconsumer: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG 
    org.springframework.boot.sql.init: DEBUG 
    org.springframework.jdbc: DEBUG 
