# common setting
spring:
  application:
    name: TicketingConsumer

  main:
    web-application-type: none
  docker:
    compose:
      enabled: false

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: ${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:5}
      maximum-pool-size: ${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:20}
      connection-timeout: ${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}

  jpa:
    hibernate:
      ddl-auto: validate 
    show-sql: true 
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      continue-on-error: true
      separator: ";"

logging:
  file:
    name: ./logs/ticketing-platform.log
  level:
    root: INFO
    org.java.rabbitcombinedconsumer: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG 
    org.springframework.boot.sql.init: DEBUG 
    org.springframework.jdbc: DEBUG 